# Generated by Django 4.0.2 on 2022-02-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='menu',
        ),
        migrations.AddField(
            model_name='commande',
            name='menus',
            field=models.ManyToManyField(related_name='menu_commande', to='restaurantapp.Menu'),
        ),
    ]
