# Generated by Django 4.0.2 on 2022-02-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_remove_commande_menus_commande_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='status',
        ),
    ]
