# Generated by Django 4.0.2 on 2022-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_remove_menu_date_add_remove_menu_date_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.FileField(default=1, upload_to='image_menu'),
            preserve_default=False,
        ),
    ]
